version: '3.8'

services:
  modbus-front:
    container_name: iot-monitor-frontend
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_WEBSOCKET_URL=http://host.docker.internal:3003
      - NEXT_PUBLIC_APP_NAME=${NEXT_PUBLIC_APP_NAME:-Monitor IoT}
      - NEXT_PUBLIC_MAX_DATA_POINTS=${NEXT_PUBLIC_MAX_DATA_POINTS:-20}
    healthcheck:
      test:
        [
          'CMD',
          'wget',
          '--no-verbose',
          '--tries=1',
          '--spider',
          'http://localhost:3000',
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - iot-monitor-network

networks:
  iot-monitor-network:
    name: iot-monitor-network
    driver: bridge
